# window.onload = ->
#   # Get a reference to the canvas object
#   canvas = document.getElementById('myCanvas')
#   # Create an empty project and a view for the canvas:
#   paper.setup canvas
#   # Create a Paper.js Path to draw a line into it:
#   path = new (paper.Path)
#   # Give the stroke a color
#   path.strokeColor = 'black'
#   start = new (paper.Point)(100, 100)
#   # Move to start and draw a line from there
#   path.moveTo start
#   # Note that the plus operator on Point objects does not work
#   # in JavaScript. Instead, we need to call the add() function:
#   path.lineTo start.add([
#     200
#     -50
#   ])
#   # Draw the view now:
#   paper.view.draw()
#   return


paper.install window

window.onload = ->
  paper.setup 'myCanvas'
  d3.select('#myCanvas').style("height", 800)
  from = new Point(40, 40)
  to = new Point(180, 180)
  path = new Path.Circle(new Point(80, 50), 30) #Path.Line(from, to)
  rec = new (Path.Rectangle)([
    75
    75
  ], [
    100
    100
  ])
  path.strokeColor = 'black'


  gui = new (dat.GUI)
  params = new (->
    @speed = 0
    @target = 0
    return
  )
  gui.add(params, 'speed', -50, 50).onChange (e) ->
    # e is the update value
    view.onFrame = (event) ->
      # On each frame, rotate the path by 3 degrees:
      path.rotate e
      return

    return
    console.log e
    return


    
    

  # ---
  # generated by js2coffee 2.2.0